# Generated by Django 3.2.13 on 2022-05-09 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('attachment_link', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(choices=[('IT', 'IT실'), ('BN', '경영지원'), ('BR', '브랜드전략'), ('CD', '여신관리')], default='IT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=50)),
                ('board_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleIssue',
            fields=[
                ('responsible_issue_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('responsible_issue_name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibleIssue', to='ITSApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('subscribe_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('picture', models.URLField(max_length=2000, null=True)),
                ('responsibleIssue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='ITSApp.responsibleissue')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('Responsibility_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('responsibility_type', models.CharField(max_length=20)),
                ('responsible_issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility', to='ITSApp.responsibleissue')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('priority', models.CharField(choices=[('F', '긴급'), ('M', '보통'), ('S', '여유')], default='M', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='ITSApp.board')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('comment_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='ITSApp.comment')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='ITSApp.project'),
        ),
    ]
