# Generated by Django 3.2.13 on 2022-05-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attachment'),
        ),
    ]
