# Generated by Django 3.2.13 on 2022-05-26 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ITSApp', '0003_auto_20220526_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='responsible_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ITSApp.responsibleissue'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
