# Generated by Django 3.2.13 on 2022-05-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ITSApp', '0011_alter_comment_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='ITSApp.issue'),
            preserve_default=False,
        ),
    ]
