# Generated by Django 3.2.13 on 2022-05-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSApp', '0013_rename_subscribe_id_subscribe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
