# Generated by Django 3.2.13 on 2022-05-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSApp', '0015_alter_subscribe_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='deadline',
            field=models.CharField(max_length=20),
        ),
    ]
