# Generated by Django 3.2.13 on 2022-06-07 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ITSApp', '0018_rename_title_board_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility', to=settings.AUTH_USER_MODEL),
        ),
    ]
