# Generated by Django 3.2.13 on 2022-06-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSApp', '0019_alter_responsibility_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='order',
            field=models.IntegerField(default=3),
        ),
    ]
