# Generated by Django 3.2.13 on 2022-06-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSApp', '0022_alter_subscribe_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='flag',
        ),
    ]
